on:
  workflow_displatch:
  schedule:
  - cron: 0 0 * * 3 # every Wednesday

name: Update Packages
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set remote url
      run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: package-update
      uses: taichi/actions-package-update@master
      env:
        AUTHOR_EMAIL: bravo-kernel@users.noreply.github.com
        AUTHOR_NAME: bravo-kernel
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: debug
      with:
        args: -u --packageFile package.json --loglevel verbose
